language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "stable"
  - "lts/*"

# Travis CI uses "npm ci" by default because there is a package-lock.json file
install:
  - npm ci --cache .npm --prefer-offline --loglevel notice

script:
  - npm audit
